/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.libmngmsys.librarysystem;


import com.libmngmsys.librarysystem.Books;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import com.libmngmsys.librarysystem.Books;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class admindbform extends javax.swing.JFrame {

    /**
     * Creates new form admindbform
     */
    
    com.libmngmsys.librarysystem.Books books = new com.libmngmsys.librarysystem.Books();
    public admindbform() {
        initComponents();
        
       jLabel_emptybookname.setVisible(false);
       jLabel_emptymainclass.setVisible(false);
       jLabel_emptysubclass.setVisible(false);
       jLabel_emptylocation.setVisible(false);
       
       populateJtablewithBooks();
       

    }
       //function to populate table with books
    private void populateJtablewithBooks() {
        ArrayList<com.libmngmsys.librarysystem.Books> bookList = books.bookList();
        
        //jtablecolumns
        String[] colNames = {"ID", "bookname", "Main Class", "Sub Class", "Location", "File Name"};
        
       DefaultTableModel model = new DefaultTableModel(colNames, 0); // Initialize model without data
        //row
     for (com.libmngmsys.librarysystem.Books book : bookList) {
        Object[] row = {
            book.getId(),
            book.getBookname(),
            book.getMainclass(),
            book.getSubclass(),
            book.getLocation(),
           book.getFilename()
        };
        model.addRow(row);
    }

    jTable_books.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_books = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_bookname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox_mainclass = new javax.swing.JComboBox<>();
        jLabel_emptylocation = new javax.swing.JLabel();
        jLabel_emptysubclass = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_subclass = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField_location = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel_emptybookname = new javax.swing.JLabel();
        jButton_add = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton_remove = new javax.swing.JButton();
        jButton_choosefile = new javax.swing.JButton();
        jLabel_path = new javax.swing.JLabel();
        jLabel_emptymainclass = new javax.swing.JLabel();
        jButton_clear = new javax.swing.JButton();
        jButton_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTable_books.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_books.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_booksMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_books);

        jLabel1.setText("Book ID:");

        jTextField_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_idActionPerformed(evt);
            }
        });

        jLabel2.setText("Book Name:");

        jLabel3.setText("Main Class:");

        jComboBox_mainclass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z" }));

        jLabel_emptylocation.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_emptylocation.setText("*required");
        jLabel_emptylocation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_emptylocationMouseClicked(evt);
            }
        });

        jLabel_emptysubclass.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_emptysubclass.setText("*required");
        jLabel_emptysubclass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_emptysubclassMouseClicked(evt);
            }
        });

        jLabel6.setText("Sub Class:");

        jLabel8.setText("Location");

        jLabel9.setText("Photo:");

        jLabel_emptybookname.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_emptybookname.setText("*required");
        jLabel_emptybookname.setFocusable(false);
        jLabel_emptybookname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_emptybooknameMouseClicked(evt);
            }
        });

        jButton_add.setText("Add");
        jButton_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addActionPerformed(evt);
            }
        });

        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton_remove.setText("Remove");
        jButton_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_removeActionPerformed(evt);
            }
        });

        jButton_choosefile.setText("Select File");
        jButton_choosefile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_choosefileMouseClicked(evt);
            }
        });
        jButton_choosefile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_choosefileActionPerformed(evt);
            }
        });

        jLabel_path.setText("No Photo Selected");
        jLabel_path.setToolTipText("");

        jLabel_emptymainclass.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_emptymainclass.setText("*required");
        jLabel_emptymainclass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_emptymainclassMouseClicked(evt);
            }
        });

        jButton_clear.setText("Clear Field");
        jButton_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_clearActionPerformed(evt);
            }
        });

        jButton_back.setText("Back");
        jButton_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9)
                            .addComponent(jLabel1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(jLabel_emptylocation))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel_emptysubclass))
                            .addComponent(jTextField_id)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel_emptymainclass))
                            .addComponent(jTextField_subclass, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_emptybookname))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel_path, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_choosefile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_location, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                            .addComponent(jComboBox_mainclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_bookname)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_clear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_remove)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_back)))
                .addGap(114, 114, 114))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel_emptybookname))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_bookname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel_emptymainclass))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_mainclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel_emptysubclass))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_subclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel_emptylocation))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_path)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_choosefile))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_add)
                    .addComponent(jButton2)
                    .addComponent(jButton_clear)
                    .addComponent(jButton_remove)
                    .addComponent(jButton_back))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_idActionPerformed

    private void jButton_choosefileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_choosefileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_choosefileActionPerformed

    private void jButton_choosefileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_choosefileMouseClicked
        // TODO add your handling code here:
        JFileChooser filechooser = new JFileChooser();
        filechooser.setDialogTitle("Set Photo");
 
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "jpeg", "png");
        filechooser.setFileFilter(filter);
        
        int fileState = filechooser.showSaveDialog(null);
        
        if(fileState == JFileChooser.APPROVE_OPTION) {
            java.io.File selectedFile = filechooser.getSelectedFile();

            // Extract file name without path
            String path = selectedFile.getName();
            
            jLabel_path.setText(path);
        }
    }//GEN-LAST:event_jButton_choosefileMouseClicked

    private void jButton_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addActionPerformed
        
        String bookname = jTextField_bookname.getText();
        String mainclass = jComboBox_mainclass.getSelectedItem().toString();
        String subclass = jTextField_subclass.getText();
        String location = jTextField_location.getText();
        String filename = jLabel_path.getText();
        
        if(bookname.isEmpty()) {
            jLabel_emptybookname.setVisible(true);
        } else if (mainclass == null || mainclass.toString().isEmpty()) {
            jLabel_emptymainclass.setVisible(true);
        } else if (subclass.isEmpty()) {
            jLabel_emptysubclass.setVisible(true);
        } else if (location.isEmpty()){
            jLabel_emptylocation.setVisible(true);
        } else if (filename == null || filename.isEmpty()) {
            System.out.println("Error");
        } else {
            books.addBook(bookname, mainclass, subclass, location, filename);
            populateJtablewithBooks();
        }
    }//GEN-LAST:event_jButton_addActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //editbook
        String bookname = jTextField_bookname.getText();
        String mainclass = jComboBox_mainclass.getSelectedItem().toString();
        String subclass = jTextField_subclass.getText();
        String location = jTextField_location.getText();
        String filename = jLabel_path.getText();
        
        if(bookname.isEmpty()){
            System.out.println("Error");
        } else if (mainclass.isEmpty()){
            System.out.println("ERror");
        } else {
            try{
                int id = Integer.parseInt(jTextField_id.getText());
                books.editBook(id, bookname, mainclass, subclass, location, filename);
                populateJtablewithBooks();
            } catch(NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Inavlid Book ID" + ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_removeActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(jTextField_id.getText());
            books.removeBook(id);
            populateJtablewithBooks();
        } catch(NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Invalid Book ID" + ex.getMessage());
        }
    }//GEN-LAST:event_jButton_removeActionPerformed

    private void jTable_booksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_booksMouseClicked
        // TODO add your handling code here:
        int index = jTable_books.getSelectedRow();
        
        //get values
        String id = jTable_books.getValueAt(index, 0).toString();
        String bookname = jTable_books.getValueAt(index, 1).toString();
        String mainclass = jTable_books.getValueAt(index,2).toString();
        String subclass = jTable_books.getValueAt(index, 3).toString();
        String location = jTable_books.getValueAt(index, 4).toString();
        String filename = jTable_books.getValueAt(index, 5).toString();
        
        //show data in the info field
        jTextField_id.setText(id);
        jTextField_bookname.setText(bookname);
        jComboBox_mainclass.setSelectedItem(mainclass);
        jTextField_subclass.setText(subclass);
        jTextField_location.setText(location);
        jLabel_path.setText(filename);
    }//GEN-LAST:event_jTable_booksMouseClicked

    private void jLabel_emptybooknameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_emptybooknameMouseClicked
        jLabel_emptybookname.setVisible(false);
    }//GEN-LAST:event_jLabel_emptybooknameMouseClicked

    private void jLabel_emptymainclassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_emptymainclassMouseClicked
        jLabel_emptymainclass.setVisible(false);
    }//GEN-LAST:event_jLabel_emptymainclassMouseClicked

    private void jLabel_emptysubclassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_emptysubclassMouseClicked
        jLabel_emptysubclass.setVisible(false);
    }//GEN-LAST:event_jLabel_emptysubclassMouseClicked

    private void jLabel_emptylocationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_emptylocationMouseClicked
        jLabel_emptylocation.setVisible(false);
    }//GEN-LAST:event_jLabel_emptylocationMouseClicked

    private void jButton_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_clearActionPerformed
       jTextField_bookname.setText("");
       jTextField_id.setText("");
       jLabel_path.setText("No Photo Selected");
       jComboBox_mainclass.setSelectedIndex(0);
       jTextField_subclass.setText("");
       jTextField_location.setText("");
    }//GEN-LAST:event_jButton_clearActionPerformed

    private void jButton_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_backActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admindbform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admindbform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admindbform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admindbform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admindbform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_add;
    private javax.swing.JButton jButton_back;
    private javax.swing.JButton jButton_choosefile;
    private javax.swing.JButton jButton_clear;
    private javax.swing.JButton jButton_remove;
    private javax.swing.JComboBox<String> jComboBox_mainclass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_emptybookname;
    private javax.swing.JLabel jLabel_emptylocation;
    private javax.swing.JLabel jLabel_emptymainclass;
    private javax.swing.JLabel jLabel_emptysubclass;
    private javax.swing.JLabel jLabel_path;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_books;
    private javax.swing.JTextField jTextField_bookname;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_location;
    private javax.swing.JTextField jTextField_subclass;
    // End of variables declaration//GEN-END:variables
}
